CLI
Rebryk/SPbAU-Software-Design pull request #1
Opened 2016-09-12 21:58 UTC by Rebryk

2016-09-19 17:41 UTC, yurii-litvinov requested changes

2016-11-06 17:23 UTC, yurii-litvinov requested changes
А зачем .class-файлы? :)
Ещё надо заресолвить конфликты, чтобы можно было смерджить. 
Ещё, кстати, набор тестов жалковат, например, команда pwd вообще не покрыта.

2016-11-06 17:23 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/parsing.kt
> +            .joinToString(" ")
При таком подходе не работает подстановка, если переменная не отделена пробелом от остальной строки, например, 
```
x = qwerty
echo "123$x"
```
Лучше было искать "$".

2016-11-12 13:51 UTC, Rebryk commented
@yurii-litvinov 
Поправил поиск. Добавил пару тестов.

2016-12-19 09:31 UTC, Rebryk commented
@yurii-litvinov 
Проверьте, плиз

2016-12-27 12:49 UTC, yurii-litvinov commented
Теперь всё хорошо, зачтена.

2016-12-27 12:49 UTC, yurii-litvinov approved these changes

2016-12-28 01:32 UTC, closed without merging