Задание №3: CD, LS.
Rebryk/SPbAU-Software-Design pull request #5
Opened 2016-10-12 08:14 UTC by LDVSOFT

- Добавил поддержку текущей директории.
- Для этого в интерфейсе `Command`, в его единственном методе `execute`, теперь передаётся и сама оболочка (`shell: Shell`).
- Добавил команды CD и LS в стилистике остальных команд (единственный аргумент).
- По дороге сами собой вычистились некоторые временные файлы и лишние точки с запятой в коде.

Мысли об архитектуре:
1. Нет выделенного парсера, вместо них — просто набор функций.
2. Встроенные команды оболочки регистрируются просто в `main`, использование оболочки вне него приведёт к их отсутствию.
3. Плохо продуман интерфейс `Command` — зачем-то `Shell` его реализует. Зачем?
   Пришлось убрать.
4. Также, слабый контракт у параметров интерфейса `Command`: там передаётся как ввод, так и параметры команды, а иногда и имя.
5. Почему-то запуск внешних команд вынесен в класс, реализующий интерфейс `Command`, называющийся "Окружение": `Environment`.

2016-12-18 21:03 UTC, yurii-litvinov commented
Возвращает код 403 при попытке спуллить изменения. Зачем приватный репозиторий? :)

2016-12-18 21:18 UTC, Rebryk commented
Он не приватный.

19 дек. 2016 г. 12:03 AM пользователь "Yurii Litvinov" <
notifications@github.com> написал:

> Возвращает код 403 при попытке спуллить изменения. Зачем приватный
> репозиторий? :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Rebryk/SPbAU-Software-Design/pull/5#issuecomment-267846443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AECR8cfkCE_qM5oZlz80FYjgx-oXnQvZks5rJZ-pgaJpZM4KUe0c>
> .
>

2016-12-18 21:19 UTC, yurii-litvinov commented
Я про https://github.com/LDVSOFT/SPbAU-Software-Design

2016-12-18 21:22 UTC, yurii-litvinov requested changes
Ещё нужны тесты на новые команды

2016-12-18 22:23 UTC, Rebryk commented
@yurii-litvinov 
Они в ветке cli

2016-12-19 09:11 UTC, LDVSOFT commented
А если я скажу вам, что это МОЙ код? )

2016-12-19 09:28 UTC, Rebryk commented
Лооол

2016-12-23 23:08 UTC, LDVSOFT commented
Спасибо ГитХабу, я сюда больше не могу коммитить сходу. Перенёс всё [сюда](https://github.com/LDVSOFT/SPbAU-Software-Design/pull/1).

2016-12-23 23:08 UTC, closed without merging