Chat
Rebryk/SPbAU-Software-Design pull request #6
Opened 2016-10-30 12:18 UTC by rebryk

@yurii-litvinov

2016-12-27 21:44 UTC, yurii-litvinov requested changes
- Непонятно, как задать порт, на котором сервер слушает подключения или как узнать порт, на котором поднялся сервер
- На текст serverIP по умолчанию ругается, что он в неверном формате (порт не указан ведь)
Поправьте, пожалуйста.

2016-12-27 21:44 UTC, yurii-litvinov commented on .idea/workspace.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Это в гите не нужно

2016-12-27 21:44 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/messenger/Messenger.kt
> +interface Messenger {
Написать комментарии хотя бы к ключевым интерфейсам всё-таки необходимо. Хорошо, если комментарии будут к каждому классу и каждому паблик-методу, но на этом я не настаиваю.

2016-12-28 01:30 UTC, Rebryk commented
Поправил.
Теперь порт сервера задается в аргументах при запуске.

2016-12-28 05:37 UTC, yurii-litvinov commented
Тогда по-хорошему надо выводить подсказку по аргументам, если они не переданы, а не падать :) Но ладно, зачтена.

2020-08-02 17:37 UTC, closed without merging